Sombra.Web/ViewModels/Home/CharityActionItemViewModel.cs
using System;

namespace Sombra.Web.ViewModels.Home
{
    public class CharityActionItemViewModel
    {
        public Guid CharityActionKey { get; set; }
        public string Name { get; set; }
        public string CoverImage { get; set; }
        public string OrganiserImage { get; set; }
        public string OrganiserUserName { get; set; }
        public decimal TargetAmount { get; set; }
        public decimal CollectedAmount { get; set; }
        public DateTime ActionEndDateTime { get; set; }
    }
}

Sombra.Web/ViewModels/Shared/CharityActionItemViewModel.cs
using System;

namespace Sombra.Web.ViewModels.Shared
{
    public class CharityActionItemViewModel
    {
        public Guid CharityActionKey { get; set; }
        public string Name { get; set; }
        public string CoverImage { get; set; }
        public string Logo { get; set; }
        public string OrganiserImage { get; set; }
        public string OrganiserUserName { get; set; }
        public decimal TargetAmount { get; set; }
        public decimal CollectedAmount { get; set; }
        public DateTime ActionEndDateTime { get; set; }
    }
}

Sombra.Web/ViewModels/Shared/CharityActionsQuery.cs
namespace Sombra.Web.ViewModels.Shared
{
    public class CharityActionsQuery
    {
        public int PageSize { get; set; }
        public int PageNumber { get; set; }
    }
}

Sombra.Web/ViewModels/Shared/CharityActionsViewModel.cs
using System.Collections.Generic;

namespace Sombra.Web.ViewModels.Shared
{
    public class CharityActionsViewModel
    {
        public List<CharityActionItemViewModel> CharityActions { get; set; }
    }
}

Sombra.Web/ViewModels/Shared/PagedViewModel.cs
namespace Sombra.Web.ViewModels.Shared
{
    public class PagedViewModel
    {
        public int PageNumber { get; set; }
        public int PageSize { get; set; }
        public int TotalNumberOfResults { get; set; }
    }
}

Sombra.Web/ViewModels/Shared/StoryViewModel.cs
namespace Sombra.Web.ViewModels.Shared
{
    public class StoryViewModel
    {
        public string AuthorName { get; set; }
        public string UrlComponent { get; set; }
        public string CoverImage { get; set; }
        public string QuoteText { get; set; }
        public string CharityUrl { get; set; }
    }
}

Sombra.Web/Controllers/CharityController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Sombra.Messaging.Requests.Charity;
using Sombra.Messaging.Requests.Donate;
using Sombra.Messaging.Requests.Story;
using Sombra.Web.Infrastructure;
using Sombra.Web.Infrastructure.Messaging;
using Sombra.Web.ViewModels.Charity;
using Sombra.Web.ViewModels.Shared;
using GetCharitiesRequest = Sombra.Messaging.Requests.Charity.GetCharitiesRequest;
using GetCharityActionsRequest = Sombra.Messaging.Requests.CharityAction.GetCharityActionsRequest;

namespace Sombra.Web.Controllers
{
    public class CharityController : Controller
    {
        private readonly ICachingBus _bus;
        private readonly IMapper _mapper;

        public CharityController(ICachingBus bus, IMapper mapper)
        {
            _bus = bus;
            _mapper = mapper;
        }

        [HttpGet("goede-doelen")]
        public IActionResult Search()
        {
            return View("Search");
        }

        [HttpGet]
        public async Task<IActionResult> SearchCharities(SearchQuery query)
        {
            var request = _mapper.Map<GetCharitiesRequest>(query);
            var response = await _bus.RequestAsync(request);

            if (response.IsRequestSuccessful)
            {
                var model = _mapper.Map<SearchResultsViewModel>(response);
                model.PageNumber = query.PageNumber;
                model.PageSize = query.PageSize;

                return View("_SearchResultsWrapper", model);
            }

            return View("_SearchResultsWrapper", new SearchResultsViewModel());
        }

        [HttpGet]
        [Subdomain]
        public async Task<IActionResult> Index(CharityQuery query)
        {
            var request = _mapper.Map<GetCharityByUrlRequest>(query);
            var response = await _bus.RequestAsync(request);
            if (!response.IsSuccess || !response.Charity.IsApproved) return new StatusCodeResult((int) HttpStatusCode.NotFound);

            var model = _mapper.Map<CharityViewModel>(response.Charity);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetCharityActions(CharityActionsByCharityQuery query)
        {
            var request = _mapper.Map<GetCharityActionsRequest>(query);
            var response = await _bus.RequestAsync(request);
            if (!response.IsRequestSuccessful) return new StatusCodeResult((int)HttpStatusCode.ServiceUnavailable);

            var model = _mapper.Map<CharityActionsViewModel>(response);
            return PartialView("_CharityActionItemsWrapper", model);
        }

        [HttpGet]
        public async Task<IActionResult> GetCharityDonations(DonationsInWeekByCharityQuery query)
        {
            var request = _mapper.Map<GetCharityTotalRequest>(query);
            var response = await _bus.RequestAsync(request);
            if (!response.IsRequestSuccessful) return new StatusCodeResult((int)HttpStatusCode.ServiceUnavailable);

            var model = _mapper.Map<DonationsViewModel>(response);
            return PartialView("~/Views/Charity/_DonationItemsWrapper.cshtml", model);
        }

        [HttpGet]
        public async Task<IActionResult> GetCharityStory(CharityStoryQuery query)
        {
            var request = _mapper.Map<GetStoriesRequest>(query);
            var response = await _bus.RequestAsync(request);
            if (!response.IsRequestSuccessful) return new StatusCodeResult((int)HttpStatusCode.ServiceUnavailable);
            if (response.TotalNumberOfResults == 0) return new StatusCodeResult((int)HttpStatusCode.NotFound);

            var model = _mapper.Map<StoryViewModel>(response.Results.First());
            return PartialView("_CharityStory", model);
        }
    }
}

Sombra.Web/Controllers/DashboardController.cs
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Sombra.Messaging.Requests.Story;
using Sombra.Web.Infrastructure.Messaging;
using Sombra.Web.ViewModels.Dashboard;

namespace Sombra.Web.Controllers
{
    public class DashboardController : Controller
    {
        private readonly ICachingBus _bus;
        private readonly IMapper _mapper;

        public DashboardController(ICachingBus bus, IMapper mapper)
        {
            _bus = bus;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("goed-doel-aanmelden")]
        public IActionResult SignUpCharity()
        {
            return View();
        }

        [HttpGet("deel-jouw-verhaal")]
        public IActionResult CreateStory()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetCharities()
        {
            var request = new GetCharitiesRequest();
            var response = await _bus.RequestAsync(request);
            if (!response.IsRequestSuccessful) return new StatusCodeResult((int)HttpStatusCode.ServiceUnavailable);

            var charities = _mapper.Map<List<Charity>>(response.Charities);
            return Json(charities);
        }
    }
}

Sombra.Web/Controllers/DonateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Sombra.Messaging.Requests.Donate;
using Sombra.Web.Infrastructure.Messaging;
using Sombra.Web.ViewModels;
using Sombra.Web.ViewModels.Donate;

namespace Sombra.Web.Controllers
{
    public class DonateController : Controller
    {
        private readonly ICachingBus _bus;
        private readonly IMapper _mapper;

        public DonateController(ICachingBus bus, IMapper mapper)
        {
            _bus = bus;
            _mapper = mapper;
        }

        [HttpGet("doneren")]
        public IActionResult Index()
        {
            return View("Index");
        }

        [HttpPost("doneren")]
        public async Task<IActionResult> Index(DonateViewModel model)
        {
            if(model.UserName == null) 
            { 
                model.IsAnonymous = true;
            }
            var request = _mapper.Map<MakeDonationRequest>(model);
            if(!request.IsAnonymous){
                if(HttpContext.User.Claims.Any(c => c.Type == ClaimTypes.Sid)){
                    request.UserKey = Guid.Parse(HttpContext.User.Claims.Single(c => c.Type == ClaimTypes.Sid).Value);
                }
                else
                {
                    request.UserKey = null;
                }
            }
            var response = await _bus.RequestAsync(request);
            if(response.IsRequestSuccessful){
                var viewModel = _mapper.Map<DonateResultViewModel>(response);

                return View("_ThankYou", viewModel);
            }

            HttpContext.Response.StatusCode = 400;
            return Content("Something has gone wrong"); 
        }

        [HttpGet]
        public async Task<IActionResult> GetCharities()
        {
            var request = new GetCharitiesRequest();
            var response = await _bus.RequestAsync(request);
            if (!response.IsRequestSuccessful) return new StatusCodeResult((int) HttpStatusCode.ServiceUnavailable);

            var charities = _mapper.Map<List<Charity>>(response.Charities);
            return Json(charities);
        }

        [HttpGet]
        public async Task<IActionResult> GetCharityActions(string charityKey)
        {
            var charityKeyIsValidGuid = Guid.TryParse(charityKey, out var charityKeyGuid);
            if (!charityKeyIsValidGuid) return new StatusCodeResult((int) HttpStatusCode.BadRequest);

            var request = new GetCharityActionsRequest
            {
                CharityKey = charityKeyGuid
            };
            var response = await _bus.RequestAsync(request);
            if (!response.IsRequestSuccessful) return new StatusCodeResult((int) HttpStatusCode.ServiceUnavailable);

            var charityActions = _mapper.Map<List<CharityAction>>(response.CharityActions);
            return Json(charityActions);
        }

        [HttpGet]
        public IActionResult Email()
        {
            return View("Email");
        }
    }
}

Sombra.Web/Controllers/MissionController.cs
using Microsoft.AspNetCore.Mvc;

namespace Sombra.Web.Controllers
{
    public class MissionController : Controller
    {
        [HttpGet("onze-missie")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Sombra.Web/Views/Shared/_CharityActionItem.cshtml
@using Sombra.Web.Infrastructure
@model Sombra.Web.ViewModels.Shared.CharityActionItemViewModel
@{
    var progress = Model.CollectedAmount / Model.TargetAmount * 100;
    var progressPercentage = progress > 100 ? 100 : progress;
}
<div class="carousel-cell">
    <div class="carousel-container">
        <div class="carousel-background">
            <div class="carousel-logo" style="background-image: url(@Model.Logo);"></div>
            <div class="carousel-progress-bar">
                <div class="carousel-progress" style="width: @progressPercentage%;"></div>
            </div>
        </div>
        <div class="carousel-body">
            <label class="carousel-date">@Model.ActionEndDateTime.ToFormattedString()</label>
            <h4 class="carousel-title">@Model.Name</h4>
            <img class="carousel-poster-image" src="@Model.OrganiserImage">
            <label class="carousel-poster-name">@Model.OrganiserUserName</label>

            <div class="carousel-money-holder">
                <label class="carousel-reached">&euro; @Model.CollectedAmount.ToFormattedString()</label>
                <label class="carousel-goal">behaald van &euro; @Model.TargetAmount.ToFormattedString()</label>
            </div>
        </div>
    </div>
</div>

Sombra.Web/Views/Shared/_CharityActionItemsWrapper.cshtml
@using Sombra.Web.Infrastructure.Extensions
@model Sombra.Web.ViewModels.Shared.CharityActionsViewModel

@if (Model.CharityActions != null)
{
    <h3 class="title">Lopende acties</h3>
    <div class="slider-container">
        <div class="main-carousel">
            @foreach (var charityAction in Model.CharityActions)
            {
                @await Html.PartialAsync("_CharityActionItem", charityAction)
            }
        </div>
        <div class="button button--previous"></div>
        <div class="button button--next"></div>
    </div>

    <div class="action-buttons">
        <div class="all-actions colored-button">
            <a href="@Html.BaseUrl(Url.Action("CharityActions", "Home"))"></a>
            <span class="monster-700">Bekijk alle acties</span>
        </div>
        <div class="make-actions blank-button">
            <a href="#"></a>
            <span class="monster-700">Start een actie</span>
        </div>
    </div>
}

Sombra.Web/Views/Shared/_DisclaimerModal.cshtml
<div id="disclaimer-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title monster-700">Disclaimer</h3>
            </div>
            <div class="modal-body">
                <p>
                    Ikdoneer.nu is een platform dat is bedacht, gebouwd en ontworpen in het kader van een schoolproject. Zeven studenten van de Hogeschool Rotterdam hebben dit <strong>fictieve</strong> platform ontwikkeld. Dit wil zeggen dat u hier dus niet daadwerkelijk een goed doel kunt aanmelden, kunt doneren, een actie kan aanmaken of uw verhaal kunt delen. De informatie over de genoemde goede doelen en/of stichtingen is dan ook <strong>niet geheel werkelijk of actueel</strong>. Bezoek voor werkelijke en actuele informatie de websites van de goede doelen zelf.
                </p>
            </div>
            <div class="modal-footer">
                <div id="close-disclaimer-modal" class="big-button colored-button" data-dismiss="modal"><span>Ik begrijp het</span></div>
            </div>
        </div>
    </div>
</div>

Sombra.Web/Views/Shared/_Layout.cshtml
@using Sombra.Web.Infrastructure.Extensions
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@RenderSection("Title", true) - ikdoneer.nu</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,300i,400,600,700,800|Source+Sans+Pro:300,300i,400,700" rel="stylesheet">
    <link href="~/favicon.png" rel="icon" type="image/png" />
    <link href="~/favicon.png" rel="apple-touch-icon" type="image/png" />
    @RenderSection("Styles", required: false)
</head>

<body>
    <nav id="header">
        <div class="fixed-header">
                <a href="@Html.HomeUrl()" class="header-logo">
            </a>

            <div class="header-big-menu">
                <ul class="monster-200">

                    <li><a href="@Html.BaseUrl(Url.Action("Search", "Charity"))" id="header-goede-doelen">Goede doelen</a></li>
                    <li><a href="@Html.BaseUrl(Url.Action("CharityActions", "Home"))" id="header-acties">Acties</a></li>
                    <li><a href="@Html.BaseUrl(Url.Action("Index", "Story"))" id="header-verhalen">Verhalen</a></li>
                    <li><a href="@Html.BaseUrl(Url.Action("Index", "Mission"))" id="header-missie">Onze missie</a></li>
                </ul>
            </div>

            <div class="header-icon-menu">
                <ul>
                    <li>
                        <a class="icon-search" href="#"></a>
                    </li>
                     <li>
                        <a class="icon-user-circle" href="#"></a>
                    </li>
                    <li>
                        <div class="donate-button colored-button">
                            <a href="@Url.Action("Index", "Donate")"></a>
                            <div class="arrow"></div>
                            <span>Doneer nu</span>
                        </div>
                    </li> 
                </ul>
            </div>
        </div>
    </nav>


    <div class="body-content container">
        @RenderBody()
        </div>

<footer>
    <div class="footer-holder">
        <div class="container"></div>
        <div class="row">
            <div class="col-md-2">
                <div>
                    <ul>
                        <li><label><span>Ik Doneer Nu</span></label></li>
                        <li><a href="@Html.BaseUrl(Url.Action("Search", "Charity"))">Goede doelen</a></li>
                        <li><a href="@Html.BaseUrl(Url.Action("CharityActions", "Home"))">Acties</a></li>
                        <li><a href="@Html.BaseUrl(Url.Action("Index", "Story"))">Verhalen</a></li>
                        <li><a href="@Html.BaseUrl(Url.Action("Index", "Mission"))">Onze missie</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="@Html.BaseUrl(Url.Action("Index", "Dashboard"))">Log in</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <div>
                    <ul>
                        <li><label><span>Diensten voor</span></label></li>
                        <li><a href="#">Donateurs</a></li>
                        <li><a href="@Url.Action("Search", "Charity")">Goede doelen</a></li>
                        <li><a href="#">Acties</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <div>
                    <ul>
                        <li><label><span>Over doneren</span></label></li>
                        <li><a href="#">ANBI</a></li>
                        <li><a href="#">Belasting</a></li>
                        <li><a href="#">Betalingen</a></li>
                        <li><label><a href="@Html.BaseUrl(Url.Action("Index", "Donate"))">Doneer nu</a></label></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 updateArea">
                <label><a href="#">Updates</a></label>

                <p>Meld je aan voor de nieuwsvideo en blijf op de hoogte van de laatste updates.</p>

                <div class="sign-up-news">
                    <form action="action_page.php" id="form1">

                        <div class="email-holder">
                            <input type="text" placeholder="E-mailadres" name="mail" required>
                            <button type="submit" form="form1" value="Submit"><div class="footer-email-arrow"></div></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="footer-line"></div>
        <div class="footer-info">
            <div class="footer-info-left">
                <p class="footer-copyright">&#xa9; 2018 ikdoneer.nu</p>
                <p class="footer-privacy">Privacy</p>
                <p class="footer-cookies">Cookies</p>
                <p class="footer-help">Help</p>
            </div>
            <div class="footer-info-right">
                <a href="https://facebook.com" class="footer-facebook"></a>
                <a href="https://twitter.com/ikdoneernu" class="footer-twitter"></a>
                <a href="https://instagram.com" class="footer-instagram"></a>
                <a href="https://youtube.com" class="footer-youtube"></a>
            </div>
        </div>
    </div>
</footer>
    @await Html.PartialAsync("_DisclaimerModal")

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.7/jquery.validate.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
    <script src="~/js/selectize.min.js"></script>
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

Sombra.Web/Views/Shared/_Pagination.cshtml
@model Sombra.Web.ViewModels.Shared.PagedViewModel
@{
    Layout = null;
    var totalPages = (int)(Math.Ceiling((double)Model.TotalNumberOfResults / Model.PageSize) + 0.5);
    var pagesToDisplay = 5;

    var firstPageToDisplay = 1;
    var lastPageToDisplay = totalPages;
    var pageNumbersToDisplay = lastPageToDisplay;
    var tooMany = false;

    if (totalPages > pagesToDisplay)
    {
        var maxPageNumbersToDisplay = pagesToDisplay;
        firstPageToDisplay = Model.PageNumber - maxPageNumbersToDisplay / 2;
        if (firstPageToDisplay < 1)
        {
            firstPageToDisplay = 1;
        }

        pageNumbersToDisplay = maxPageNumbersToDisplay;
        lastPageToDisplay = firstPageToDisplay + pageNumbersToDisplay - 1;
        if (lastPageToDisplay > totalPages)
        {
            firstPageToDisplay = totalPages - maxPageNumbersToDisplay + 1;
            lastPageToDisplay = totalPages;
        }

        if (totalPages != lastPageToDisplay)
        {
            tooMany = true;
            lastPageToDisplay--;
        }
    }
}

<div id="pagination">
    @if (Model.PageNumber != 1)
    {
        <label class="previous-page" data-target-pagenumber="@(Model.PageNumber-1)"><img src="Assets/icons/arrow-icon-to-left.svg"></label>
    }

    @if (firstPageToDisplay != 1)
    {
        <label class="source-300" data-target-pagenumber="1">1</label>
        <label class="source-300 no-click">...</label>
        firstPageToDisplay++;
    }

    @for (var i = firstPageToDisplay; i <= lastPageToDisplay; i++)
    {
        if (i != Model.PageNumber)
        {
            <label class="source-300" data-target-pagenumber="@i">@i</label>
        }
        else
        {
            <label class="source-700 no-click" data-current-pagenumber="@i" id="current-page-number">@i</label>
        }

    }

    @if (tooMany)
    {
        <label class="source-300 no-click">...</label>
        <label class="source-300" data-target-pagenumber="@totalPages">@totalPages</label>
    }

    @if (Model.PageNumber != totalPages)
    {
        <label class="next-page" data-target-pagenumber="@(Model.PageNumber+1)"><img src="Assets/icons/icon-arrow-to-right.svg"></label>
    }
</div>